name: Ingestion functions Python CI

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/ingestion-functions-python.yml'
    - 'ingestion/functions/**'
  pull_request:
    branches: [main]
    paths:
    - '.github/workflows/ingestion-functions-python.yml'
    - 'ingestion/functions/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ingestion/functions/ci-requirements.txt -r ingestion/functions/retrieval/requirements.txt
    - name: Lint with flake8
      working-directory: ingestion/functions
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ingestion/functions
      run: pytest
    - name: Generate and upload coverage
      working-directory: ingestion/functions
      run: |
        coverage run
        coverage json
    - uses: actions/upload-artifact@v1
      with:
        name: coverage-json
        path: ingestion/functions/coverage.json
    - name: Upload test coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ingestion/functions/coverage.json